;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("abotu" "about" nil :count 6)
    ("acconut" "account" nil :count 2)
    ("account_id" "account_id" nil :count 1)
    ("accoutn" "account" nil :count 1)
    ("accoutns" "accounts" nil :count 3)
    ("acutally" "actually" nil :count 0)
    ("amoutn" "amount" nil :count 11)
    ("amoutns" "amounts" nil :count 0)
    ("anythnig" "anything" nil :count 1)
    ("aronud" "around" nil :count 2)
    ("aroudn" "around" nil :count 14)
    ("belife" "belief" nil :count 0)
    ("bulid" "build" nil :count 0)
    ("buliding" "building" nil :count 1)
    ("cehck" "check" nil :count 0)
    ("clustur" "cluster" nil :count 1)
    ("colud" "could" nil :count 2)
    ("copmlete" "complete" nil :count 0)
    ("donig" "doing" nil :count 0)
    ("empyt" "empty" nil :count 0)
    ("enuf" "enough" nil :count 1)
    ("feelnig" "feeling" nil :count 1)
    ("fro" "for" nil :count 1)
    ("fucknig" "fucking" nil :count 5)
    ("gulit" "guilt" nil :count 0)
    ("hera" "hear" nil :count 0)
    ("jsut" "just" nil :count 0)
    ("laguage" "language" nil :count 1)
    ("liike" "like" nil :count 1)
    ("linsk" "links" nil :count 3)
    ("looknig" "looking" nil :count 1)
    ("montsh" "months" nil :count 0)
    ("nad" "and" nil :count 6)
    ("networknig" "networking" nil :count 2)
    ("nto" "not" nil :count 0)
    ("picknig" "picking" nil :count 0)
    ("ponit" "point" nil :count 0)
    ("qusetion" "question" nil :count 0)
    ("saynig" "saying" nil :count 0)
    ("scuh" "such" nil :count 0)
    ("seh" "she" nil :count 1)
    ("smoe" "some" nil :count 2)
    ("taht" "that" nil :count 15)
    ("taknig" "taking" nil :count 0)
    ("talknig" "talking" nil :count 0)
    ("teh" "the" nil :count 24)
    ("tg" "thor314@gmail.com" nil :count 2)
    ("theri" "their" nil :count 1)
    ("ti" "it" nil :count 1)
    ("tihnk" "think" nil :count 3)
    ("tihs" "this" nil :count 1)
    ("tm" "thor@mintbase.io" nil :count 1)
    ("tn" "thork@tuta.io" nil :count 1)
    ("tp" "thorck@protonmail.com" nil :count 1)
    ("ustd" "understand" nil :count 3)
    ("waht" "what" nil :count 5)
    ("wokrer" "worker" nil :count 1)
    ("worknig" "working" nil :count 5)
    ("xk" "Kamphefner" nil :count 0)
    ("yseterday" "yesterday" nil :count 0)
   ))

(define-abbrev-table 'org-journal-mode-abbrev-table
  '(
    ("cb" "- [ ]" nil :count 4)
    ("gonig" "going" nil :count 4)
   ))

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("spcae" "space" nil :count 0)
    ("talknig" "talknig" nil :count 4)
    ("tgo" "TechnoloGod" nil :count 15)
    ("thinknig" "thinking" nil :count 2)
    ("wolud" "would" nil :count 2)
    ("ystd" "yesterday" nil :count 1)
   ))

(define-abbrev-table 'rust-mode-abbrev-table
  '(
    (".ts" ".to_string()" nil :count 0)
    (".tss" ".to_string()" nil :count 0)
    (".tsss" ".to_string\\(\\)" nil :count 0)
    (".tssss" ".to_string\\(\\)" nil :count 0)
    (".tsssss" ".to_string\\\\(\\\\)" nil :count 0)
    ("pln" "println!(\"{:?}\"," nil :count 0)
    ("tokne" "token" nil :count 0)
   ))

