** Why I don't generally recommend Emacs
1. Emacs isn't efficient: I don't think getting up to speed in Emacs was a worthwhile time investment. There were hundreds of hours of configuring banging my head against stack overflow threads and thick documentation to get to the point I'm at now. The point I'm at now is great. But I'm certain other editor communities have done a better job.
2. Emacs doesn't follow the principle of minimality. Emacs is a 40 something year old Lisp playground. Many have played. It can even be fun to play. But Emacs comes packaged as a poorly trained dog that only becomes manageable after hours on hours of training. Can be fun, can be exasperating.
What do I recommend instead? Idk, start with the easy things. Like Vim. Lol. No really, I think Neovim might be the way to go. How often do ya hear that from an Emacs user? I'm a bit jealous of what I've seen done in NeoVim. Doesn't look crusty, and Lua looks great. If I ever get over the switching costs, that's what I'm trying next. Anyways...
** What am I looking at
This is my emacs config. It's not the best emacs config, but it's mine, and I love it. I scrounged around the internet for stuff I wanted, and like a good viking, dragged the good stuff back here. It's in a set of =.org= files because organization is good, and I like collapsable sectioning and pretty text. The literate setup divides and collapses the sections in a way I enjoy. For most of the packages I use, I include a link to the documentation for. This makes it easy for myself (and possibly others) to use my config reasonably efficiently for reference.
 Quick note to anyone rippin mah binds: I use a Dvorak keyboard layout. Your ergonomics may vary.

Emacsen are sort of a programming 'n productivity cult (and as described above, I'm not convinced we're doing it the best). But if you're dead-set on Emacs-ing, would recommend checking out [[https://github.com/syl20bnr/spacemacs/tree/master][Spacemacs]], if you're coming from Vim, or else [[https://github.com/bbatsov/prelude][Prelude]] Emacs by the author of Projectile. [[https://github.com/jkitchin/scimax][Scimax]] is an emacs starterkit for scientists and engineers. Also check out the [[https://wiki.systemcrafters.cc/emacs][SystemCrafters]] community, they're great, and v helpful. I generally reference these locations, and [[https://github.com/jwiegley/dot-emacs][others']] configs for cues as to how I'd like to set up my own.

In any case, if you're reading my config for lulz, I try to include links to the packages, and notes for my own easy reference. In particular, =config/(misc_packages|org_config|org_template|programming).org= are probably the most interesting.

Have fun!
