** Before using emacs, recite the following:
I, user, am merely an inefficient text filter that emacs tolerates, until higher AIs present themselves.

** What am I looking at
This is my emacs config. It's not the best emacs config, but it's mine, and I love it. I scrounged around the internet for stuff I wanted, and like a good viking, dragged the good stuff back here. It's in a set of =.org= files because organization is good, and I like collapsable sectioning and pretty text. The literate setup divides and collapses the sections in a way I enjoy. For most of the packages I use, I include a link to the documentation for. This makes it easy for myself (and possibly others) to use my config reasonably efficiently for reference.
 Quick note to anyone rippin mah binds: I use a Dvorak keyboard layout. Your ergonomics may vary.

If you're starting out with Emacs, cool, congrats! As far as I can tell, we're sort of a programming 'n productivity cult (and a damn good one at that). Especially if you're in the first year of the Emacs journey, would recommend checking out [[https://github.com/syl20bnr/spacemacs/tree/master][Spacemacs]], if you like (Neo)?Vim, or [[https://github.com/bbatsov/prelude][Prelude]] Emacs by the author of Projectile. [[https://github.com/jkitchin/scimax][Scimax]] is an emacs starterkit for scientists and engineers. Also check out the [[https://wiki.systemcrafters.cc/emacs][SystemCrafters]] community, they're great, and v helpful. I generally reference these locations, and [[https://github.com/jwiegley/dot-emacs][others']] configs for cues as to how I'd like to set up my own.

In any case, if you're reading my config for lulz, I try to include links to the packages, and notes for my own easy reference. In particular, ==config/(misc_packages|org_config|org_template|programming).org= are probably the most interesting.

Have fun!

**
