* Ivy: interactive completion. Select items from lists.
Principles: Minimalism, Simplicity, Customizeability, Discoverability.
Ivy, Helm, Ido are similar. Ivy is faster, more minimalistic, easier API to extend. Helm has better grepping. Use =rigrep= to overcome this.
[[https://writequit.org/denver-emacs/presentations/2017-04-11-ivy.html][quick-guide]]. [[https://writequit.org/denver-emacs/presentations/2017-04-11-ivy.html][ivy user manual]]: suggests many keybindings.

* Reminder keys - also see global_keybinds.org
- =M-o= - hydra
- =C-M-o= - dispatching done (keep minibuffer open)
- =C-M-m= - ivy-call (keep minibuffer open)
- =C-c C-o= - while in Minibuffer, ivy-occur
- =C-c r= - ivy resume
- =C-c z/v/V= - save window layouts with [[https://oremacs.com/2016/06/27/ivy-push-view/][ivy view]]
- If defining a new function, can extend behavior with ivy-actions, [[https://oremacs.com/swiper/#example---define-a-new-command-with-several-actions][ex]]
* Installation
#+begin_src emacs-lisp
  (use-package ivy) ; intentional redundancy; counsel installs ivy.
  (setq ivy-use-virtual-buffers t ; add recents+bkmks to ivy-switch-buffer
    ivy-count-format "%d/%d ")
  (setq ivy-display-style 'fancy)
  (ivy-mode 1)
  ;; Counsel provides M-x and navigation.
  (use-package counsel)
  ;; better isearch
  (use-package swiper)
#+end_src

* Local keybinds
: #+begin_src emacs-lisp
	(add-hook 'ivy-mode-hook
    (lambda ()
      ;; local keybinds
      ))
#+end_src
* Ivy rich, more self-documenting interface
#+begin_src emacs-lisp
  (use-package ivy-rich)
  (ivy-rich-mode t)
  ;; formatting recommendation; dumb that it makes users do this
  (setcdr (assq t ivy-format-functions-alist) #'ivy-format-function-line)
  (setq ivy-rich-path-style 'abbrev) ; abbreviate paths with ~/
#+end_src
[[https://github.com/Yevgnen/ivy-rich][ivy rich]].

* Counsel-Projectile - project navigation
#+begin_src emacs-lisp
(use-package projectile)
(use-package counsel-projectile)
(projectile-load-known-projects)
#+end_src
[[https://github.com/ericdanan/counsel-projectile][counsel projectile]].

* Avy - jump to stuff like a pro
#+begin_src emacs-lisp
(use-package avy)
#+end_src
[[https://github.com/abo-abo/avy][avy]].
* [[https://github.com/Lautaro-Garcia/counsel-spotify][Counsel Spotify]] - don't leave emacs, never leave emacs
Takes a little setup thru spotify.
#+begin_src emacs-lisp
  (use-package counsel-spotify)
  (setq counsel-spotify-client-id "78c85c7b50e34d74a2e879717259b650")
  ;; set this in secrets
  ;(setq counsel-spotify-client-secret "go here: https://developer.spotify.com/dashboard/applications/78c85c7b50e34d74a2e879717259b650")
#+end_src
* [[https://github.com/raxod502/prescient.el][prescient]] completions
Turning prescient on remembers the last 1000 commands used and puts them at the top of the list
#+begin_src emacs-lisp
 (use-package prescient)
 (use-package ivy-prescient)
 (use-package company-prescient)
 (ivy-prescient-mode)
 (company-prescient-mode)
 (prescient-persist-mode) ;; save commonly used commands in var/prescient-save.el
 (setq prescient-history-length 1000)
 (setq prescient-frequency-decay .999)
#+end_src
